image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build project
    init: |
      ./build.sh
      echo "init at $(date)
      gp sync-done build
    command: |
      echo "command at $(date)

  - name: CLI
    command: |
      cd up_cli
      poetry run up wait: echo hello

  - name: LIB
    command: |
      cd up_cli
      poetry run pytest -s

vscode:
  extensions:
    - redhat.java
    - ms-azuretools.vscode-docker
    - ms-python.python
