image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build project
    init: |

      echo "init at $(date)
    command: |
      echo "command at $(date)

vscode:
  extensions:
    - redhat.java
    - ms-azuretools.vscode-docker
    - ms-python.python
