tasks:
  - name: UP CLI
    init: |   
      echo "Installed at $(date)"
    command: |
      ./install_all.sh   
      alias up='poetry run up'
      cd upcli
      echo "Ready at $(date)"

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
