image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build project
    init: |
      ./build.sh
      echo "init at $(date)
    command: |
      echo "command at $(date)

  - name: CLI
    command: |
      cd up_cli
      poetry install

  - name: LIB
    command: |
      cd up_cli
      poetry run up: echo hello

vscode:
  extensions:
    - redhat.java
    - ms-azuretools.vscode-docker
    - ms-python.python
