tasks:
  - name: CLI
    init: |
      ./install_all.sh
      alias up='poetry run up'
      echo "Installed at $(date)"
    command: |
      echo "Ready at $(date)"

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
