[tool.poetry]
name = "up_ansible"
version = "0.1.0"
description = ""
authors = ["Julio Faerman <jufaerma@redhat.com>"]
readme = "README.md"

[project]
name = "up_ansible"

[tool.poetry.dependencies]
python = "^3.12"
pluggy = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
