[tool.poetry]
name = "up"
version = "0.1.0"
description = ""
authors = ["Julio Faerman <jufaerma@redhat.com>"]
packages = [
    { include = "up" },
]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
up = 'up.main:main'
