[tool.poetry]
name = "up"
version = "0.1.333"
description = "up cli"
authors = ["Julio Faerman <jufaerma@redhat.com>"]
packages = [
    { include = "up"},
    { include = "up_lib", from="../up_lib/src" },
]

[tool.poetry.dependencies]
python = "^3.10"
up_lib = {path = "../up_lib"}

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
up = 'up.cli:cli'
