[tool.poetry]
name = "up"
version = "0.1.5"
description = "CLI frontend for up-tools"
authors = ["Julio Faerman <jufaerma@redhat.com>"]
packages = [
    { include = "up_cli", from="./src/"}
]

[tool.poetry.dependencies]
python = "^3.11"
# up_lib = "0.1.5"
up_lib = { path="../up_lib", develop=true}

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
up = 'up_cli.main:main'
